/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardLayoutRouteImport } from './routes/_dashboardLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutUsersIndexRouteImport } from './routes/_dashboardLayout/users/index'
import { Route as DashboardLayoutResourcesIndexRouteImport } from './routes/_dashboardLayout/resources/index'
import { Route as DashboardLayoutInviteCodesIndexRouteImport } from './routes/_dashboardLayout/invite-codes/index'
import { Route as DashboardLayoutEnrollmentsIndexRouteImport } from './routes/_dashboardLayout/enrollments/index'
import { Route as DashboardLayoutDashboardIndexRouteImport } from './routes/_dashboardLayout/dashboard/index'
import { Route as DashboardLayoutCoursesIndexRouteImport } from './routes/_dashboardLayout/courses/index'
import { Route as DashboardLayoutChannelsIndexRouteImport } from './routes/_dashboardLayout/channels/index'
import { Route as DashboardLayoutBroadcastIndexRouteImport } from './routes/_dashboardLayout/broadcast/index'
import { Route as DashboardLayoutArticlesIndexRouteImport } from './routes/_dashboardLayout/articles/index'
import { Route as DashboardLayoutAppSettingsIndexRouteImport } from './routes/_dashboardLayout/app-settings/index'
import { Route as DashboardLayoutAppLinksIndexRouteImport } from './routes/_dashboardLayout/app-links/index'
import { Route as DashboardLayoutActivityIndexRouteImport } from './routes/_dashboardLayout/activity/index'
import { Route as DashboardLayoutUsersIdRouteImport } from './routes/_dashboardLayout/users/$id'
import { Route as DashboardLayoutInviteCodesNewRouteImport } from './routes/_dashboardLayout/invite-codes/new'
import { Route as DashboardLayoutInviteCodesIdRouteImport } from './routes/_dashboardLayout/invite-codes/$id'
import { Route as DashboardLayoutCoursesNewRouteImport } from './routes/_dashboardLayout/courses/new'
import { Route as DashboardLayoutChannelsIdRouteImport } from './routes/_dashboardLayout/channels/$id'
import { Route as DashboardLayoutBroadcastNewRouteImport } from './routes/_dashboardLayout/broadcast/new'
import { Route as DashboardLayoutBroadcastIdRouteImport } from './routes/_dashboardLayout/broadcast/$id'
import { Route as DashboardLayoutArticlesNewRouteImport } from './routes/_dashboardLayout/articles/new'
import { Route as DashboardLayoutArticlesIdRouteImport } from './routes/_dashboardLayout/articles/$id'
import { Route as DashboardLayoutInviteCodesEditIdRouteImport } from './routes/_dashboardLayout/invite-codes/edit.$id'
import { Route as DashboardLayoutCoursesEditIdRouteImport } from './routes/_dashboardLayout/courses/edit.$id'
import { Route as DashboardLayoutChannelsEditIdRouteImport } from './routes/_dashboardLayout/channels/edit.$id'
import { Route as DashboardLayoutBroadcastEditIdRouteImport } from './routes/_dashboardLayout/broadcast/edit.$id'
import { Route as DashboardLayoutArticlesEditIdRouteImport } from './routes/_dashboardLayout/articles/edit.$id'
import { Route as DashboardLayoutCoursesSectionsSectionIdEditRouteImport } from './routes/_dashboardLayout/courses/sections/$sectionId/edit'
import { Route as DashboardLayoutCoursesLessonsLessonIdEditRouteImport } from './routes/_dashboardLayout/courses/lessons/$lessonId/edit'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutUsersIndexRoute =
  DashboardLayoutUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutResourcesIndexRoute =
  DashboardLayoutResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInviteCodesIndexRoute =
  DashboardLayoutInviteCodesIndexRouteImport.update({
    id: '/invite-codes/',
    path: '/invite-codes/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutEnrollmentsIndexRoute =
  DashboardLayoutEnrollmentsIndexRouteImport.update({
    id: '/enrollments/',
    path: '/enrollments/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutDashboardIndexRoute =
  DashboardLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesIndexRoute =
  DashboardLayoutCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChannelsIndexRoute =
  DashboardLayoutChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBroadcastIndexRoute =
  DashboardLayoutBroadcastIndexRouteImport.update({
    id: '/broadcast/',
    path: '/broadcast/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesIndexRoute =
  DashboardLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAppSettingsIndexRoute =
  DashboardLayoutAppSettingsIndexRouteImport.update({
    id: '/app-settings/',
    path: '/app-settings/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutAppLinksIndexRoute =
  DashboardLayoutAppLinksIndexRouteImport.update({
    id: '/app-links/',
    path: '/app-links/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutActivityIndexRoute =
  DashboardLayoutActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutUsersIdRoute = DashboardLayoutUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutInviteCodesNewRoute =
  DashboardLayoutInviteCodesNewRouteImport.update({
    id: '/invite-codes/new',
    path: '/invite-codes/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInviteCodesIdRoute =
  DashboardLayoutInviteCodesIdRouteImport.update({
    id: '/invite-codes/$id',
    path: '/invite-codes/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesNewRoute =
  DashboardLayoutCoursesNewRouteImport.update({
    id: '/courses/new',
    path: '/courses/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChannelsIdRoute =
  DashboardLayoutChannelsIdRouteImport.update({
    id: '/channels/$id',
    path: '/channels/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBroadcastNewRoute =
  DashboardLayoutBroadcastNewRouteImport.update({
    id: '/broadcast/new',
    path: '/broadcast/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBroadcastIdRoute =
  DashboardLayoutBroadcastIdRouteImport.update({
    id: '/broadcast/$id',
    path: '/broadcast/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesNewRoute =
  DashboardLayoutArticlesNewRouteImport.update({
    id: '/articles/new',
    path: '/articles/new',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesIdRoute =
  DashboardLayoutArticlesIdRouteImport.update({
    id: '/articles/$id',
    path: '/articles/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutInviteCodesEditIdRoute =
  DashboardLayoutInviteCodesEditIdRouteImport.update({
    id: '/invite-codes/edit/$id',
    path: '/invite-codes/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesEditIdRoute =
  DashboardLayoutCoursesEditIdRouteImport.update({
    id: '/courses/edit/$id',
    path: '/courses/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChannelsEditIdRoute =
  DashboardLayoutChannelsEditIdRouteImport.update({
    id: '/channels/edit/$id',
    path: '/channels/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutBroadcastEditIdRoute =
  DashboardLayoutBroadcastEditIdRouteImport.update({
    id: '/broadcast/edit/$id',
    path: '/broadcast/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutArticlesEditIdRoute =
  DashboardLayoutArticlesEditIdRouteImport.update({
    id: '/articles/edit/$id',
    path: '/articles/edit/$id',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesSectionsSectionIdEditRoute =
  DashboardLayoutCoursesSectionsSectionIdEditRouteImport.update({
    id: '/courses/sections/$sectionId/edit',
    path: '/courses/sections/$sectionId/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutCoursesLessonsLessonIdEditRoute =
  DashboardLayoutCoursesLessonsLessonIdEditRouteImport.update({
    id: '/courses/lessons/$lessonId/edit',
    path: '/courses/lessons/$lessonId/edit',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/broadcast/$id': typeof DashboardLayoutBroadcastIdRoute
  '/broadcast/new': typeof DashboardLayoutBroadcastNewRoute
  '/channels/$id': typeof DashboardLayoutChannelsIdRoute
  '/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/invite-codes/$id': typeof DashboardLayoutInviteCodesIdRoute
  '/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/users/$id': typeof DashboardLayoutUsersIdRoute
  '/activity': typeof DashboardLayoutActivityIndexRoute
  '/app-links': typeof DashboardLayoutAppLinksIndexRoute
  '/app-settings': typeof DashboardLayoutAppSettingsIndexRoute
  '/articles': typeof DashboardLayoutArticlesIndexRoute
  '/broadcast': typeof DashboardLayoutBroadcastIndexRoute
  '/channels': typeof DashboardLayoutChannelsIndexRoute
  '/courses': typeof DashboardLayoutCoursesIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/enrollments': typeof DashboardLayoutEnrollmentsIndexRoute
  '/invite-codes': typeof DashboardLayoutInviteCodesIndexRoute
  '/resources': typeof DashboardLayoutResourcesIndexRoute
  '/users': typeof DashboardLayoutUsersIndexRoute
  '/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/broadcast/edit/$id': typeof DashboardLayoutBroadcastEditIdRoute
  '/channels/edit/$id': typeof DashboardLayoutChannelsEditIdRoute
  '/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/broadcast/$id': typeof DashboardLayoutBroadcastIdRoute
  '/broadcast/new': typeof DashboardLayoutBroadcastNewRoute
  '/channels/$id': typeof DashboardLayoutChannelsIdRoute
  '/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/invite-codes/$id': typeof DashboardLayoutInviteCodesIdRoute
  '/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/users/$id': typeof DashboardLayoutUsersIdRoute
  '/activity': typeof DashboardLayoutActivityIndexRoute
  '/app-links': typeof DashboardLayoutAppLinksIndexRoute
  '/app-settings': typeof DashboardLayoutAppSettingsIndexRoute
  '/articles': typeof DashboardLayoutArticlesIndexRoute
  '/broadcast': typeof DashboardLayoutBroadcastIndexRoute
  '/channels': typeof DashboardLayoutChannelsIndexRoute
  '/courses': typeof DashboardLayoutCoursesIndexRoute
  '/dashboard': typeof DashboardLayoutDashboardIndexRoute
  '/enrollments': typeof DashboardLayoutEnrollmentsIndexRoute
  '/invite-codes': typeof DashboardLayoutInviteCodesIndexRoute
  '/resources': typeof DashboardLayoutResourcesIndexRoute
  '/users': typeof DashboardLayoutUsersIndexRoute
  '/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/broadcast/edit/$id': typeof DashboardLayoutBroadcastEditIdRoute
  '/channels/edit/$id': typeof DashboardLayoutChannelsEditIdRoute
  '/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboardLayout': typeof DashboardLayoutRouteWithChildren
  '/_dashboardLayout/articles/$id': typeof DashboardLayoutArticlesIdRoute
  '/_dashboardLayout/articles/new': typeof DashboardLayoutArticlesNewRoute
  '/_dashboardLayout/broadcast/$id': typeof DashboardLayoutBroadcastIdRoute
  '/_dashboardLayout/broadcast/new': typeof DashboardLayoutBroadcastNewRoute
  '/_dashboardLayout/channels/$id': typeof DashboardLayoutChannelsIdRoute
  '/_dashboardLayout/courses/new': typeof DashboardLayoutCoursesNewRoute
  '/_dashboardLayout/invite-codes/$id': typeof DashboardLayoutInviteCodesIdRoute
  '/_dashboardLayout/invite-codes/new': typeof DashboardLayoutInviteCodesNewRoute
  '/_dashboardLayout/users/$id': typeof DashboardLayoutUsersIdRoute
  '/_dashboardLayout/activity/': typeof DashboardLayoutActivityIndexRoute
  '/_dashboardLayout/app-links/': typeof DashboardLayoutAppLinksIndexRoute
  '/_dashboardLayout/app-settings/': typeof DashboardLayoutAppSettingsIndexRoute
  '/_dashboardLayout/articles/': typeof DashboardLayoutArticlesIndexRoute
  '/_dashboardLayout/broadcast/': typeof DashboardLayoutBroadcastIndexRoute
  '/_dashboardLayout/channels/': typeof DashboardLayoutChannelsIndexRoute
  '/_dashboardLayout/courses/': typeof DashboardLayoutCoursesIndexRoute
  '/_dashboardLayout/dashboard/': typeof DashboardLayoutDashboardIndexRoute
  '/_dashboardLayout/enrollments/': typeof DashboardLayoutEnrollmentsIndexRoute
  '/_dashboardLayout/invite-codes/': typeof DashboardLayoutInviteCodesIndexRoute
  '/_dashboardLayout/resources/': typeof DashboardLayoutResourcesIndexRoute
  '/_dashboardLayout/users/': typeof DashboardLayoutUsersIndexRoute
  '/_dashboardLayout/articles/edit/$id': typeof DashboardLayoutArticlesEditIdRoute
  '/_dashboardLayout/broadcast/edit/$id': typeof DashboardLayoutBroadcastEditIdRoute
  '/_dashboardLayout/channels/edit/$id': typeof DashboardLayoutChannelsEditIdRoute
  '/_dashboardLayout/courses/edit/$id': typeof DashboardLayoutCoursesEditIdRoute
  '/_dashboardLayout/invite-codes/edit/$id': typeof DashboardLayoutInviteCodesEditIdRoute
  '/_dashboardLayout/courses/lessons/$lessonId/edit': typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  '/_dashboardLayout/courses/sections/$sectionId/edit': typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/broadcast/$id'
    | '/broadcast/new'
    | '/channels/$id'
    | '/courses/new'
    | '/invite-codes/$id'
    | '/invite-codes/new'
    | '/users/$id'
    | '/activity'
    | '/app-links'
    | '/app-settings'
    | '/articles'
    | '/broadcast'
    | '/channels'
    | '/courses'
    | '/dashboard'
    | '/enrollments'
    | '/invite-codes'
    | '/resources'
    | '/users'
    | '/articles/edit/$id'
    | '/broadcast/edit/$id'
    | '/channels/edit/$id'
    | '/courses/edit/$id'
    | '/invite-codes/edit/$id'
    | '/courses/lessons/$lessonId/edit'
    | '/courses/sections/$sectionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/broadcast/$id'
    | '/broadcast/new'
    | '/channels/$id'
    | '/courses/new'
    | '/invite-codes/$id'
    | '/invite-codes/new'
    | '/users/$id'
    | '/activity'
    | '/app-links'
    | '/app-settings'
    | '/articles'
    | '/broadcast'
    | '/channels'
    | '/courses'
    | '/dashboard'
    | '/enrollments'
    | '/invite-codes'
    | '/resources'
    | '/users'
    | '/articles/edit/$id'
    | '/broadcast/edit/$id'
    | '/channels/edit/$id'
    | '/courses/edit/$id'
    | '/invite-codes/edit/$id'
    | '/courses/lessons/$lessonId/edit'
    | '/courses/sections/$sectionId/edit'
  id:
    | '__root__'
    | '/'
    | '/_dashboardLayout'
    | '/_dashboardLayout/articles/$id'
    | '/_dashboardLayout/articles/new'
    | '/_dashboardLayout/broadcast/$id'
    | '/_dashboardLayout/broadcast/new'
    | '/_dashboardLayout/channels/$id'
    | '/_dashboardLayout/courses/new'
    | '/_dashboardLayout/invite-codes/$id'
    | '/_dashboardLayout/invite-codes/new'
    | '/_dashboardLayout/users/$id'
    | '/_dashboardLayout/activity/'
    | '/_dashboardLayout/app-links/'
    | '/_dashboardLayout/app-settings/'
    | '/_dashboardLayout/articles/'
    | '/_dashboardLayout/broadcast/'
    | '/_dashboardLayout/channels/'
    | '/_dashboardLayout/courses/'
    | '/_dashboardLayout/dashboard/'
    | '/_dashboardLayout/enrollments/'
    | '/_dashboardLayout/invite-codes/'
    | '/_dashboardLayout/resources/'
    | '/_dashboardLayout/users/'
    | '/_dashboardLayout/articles/edit/$id'
    | '/_dashboardLayout/broadcast/edit/$id'
    | '/_dashboardLayout/channels/edit/$id'
    | '/_dashboardLayout/courses/edit/$id'
    | '/_dashboardLayout/invite-codes/edit/$id'
    | '/_dashboardLayout/courses/lessons/$lessonId/edit'
    | '/_dashboardLayout/courses/sections/$sectionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboardLayout/users/': {
      id: '/_dashboardLayout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardLayoutUsersIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/resources/': {
      id: '/_dashboardLayout/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof DashboardLayoutResourcesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/': {
      id: '/_dashboardLayout/invite-codes/'
      path: '/invite-codes'
      fullPath: '/invite-codes'
      preLoaderRoute: typeof DashboardLayoutInviteCodesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/enrollments/': {
      id: '/_dashboardLayout/enrollments/'
      path: '/enrollments'
      fullPath: '/enrollments'
      preLoaderRoute: typeof DashboardLayoutEnrollmentsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/dashboard/': {
      id: '/_dashboardLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/': {
      id: '/_dashboardLayout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof DashboardLayoutCoursesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/channels/': {
      id: '/_dashboardLayout/channels/'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof DashboardLayoutChannelsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/broadcast/': {
      id: '/_dashboardLayout/broadcast/'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof DashboardLayoutBroadcastIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/': {
      id: '/_dashboardLayout/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof DashboardLayoutArticlesIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/app-settings/': {
      id: '/_dashboardLayout/app-settings/'
      path: '/app-settings'
      fullPath: '/app-settings'
      preLoaderRoute: typeof DashboardLayoutAppSettingsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/app-links/': {
      id: '/_dashboardLayout/app-links/'
      path: '/app-links'
      fullPath: '/app-links'
      preLoaderRoute: typeof DashboardLayoutAppLinksIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/activity/': {
      id: '/_dashboardLayout/activity/'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardLayoutActivityIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/users/$id': {
      id: '/_dashboardLayout/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof DashboardLayoutUsersIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/new': {
      id: '/_dashboardLayout/invite-codes/new'
      path: '/invite-codes/new'
      fullPath: '/invite-codes/new'
      preLoaderRoute: typeof DashboardLayoutInviteCodesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/$id': {
      id: '/_dashboardLayout/invite-codes/$id'
      path: '/invite-codes/$id'
      fullPath: '/invite-codes/$id'
      preLoaderRoute: typeof DashboardLayoutInviteCodesIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/new': {
      id: '/_dashboardLayout/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof DashboardLayoutCoursesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/channels/$id': {
      id: '/_dashboardLayout/channels/$id'
      path: '/channels/$id'
      fullPath: '/channels/$id'
      preLoaderRoute: typeof DashboardLayoutChannelsIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/broadcast/new': {
      id: '/_dashboardLayout/broadcast/new'
      path: '/broadcast/new'
      fullPath: '/broadcast/new'
      preLoaderRoute: typeof DashboardLayoutBroadcastNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/broadcast/$id': {
      id: '/_dashboardLayout/broadcast/$id'
      path: '/broadcast/$id'
      fullPath: '/broadcast/$id'
      preLoaderRoute: typeof DashboardLayoutBroadcastIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/new': {
      id: '/_dashboardLayout/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof DashboardLayoutArticlesNewRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/$id': {
      id: '/_dashboardLayout/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof DashboardLayoutArticlesIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/invite-codes/edit/$id': {
      id: '/_dashboardLayout/invite-codes/edit/$id'
      path: '/invite-codes/edit/$id'
      fullPath: '/invite-codes/edit/$id'
      preLoaderRoute: typeof DashboardLayoutInviteCodesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/edit/$id': {
      id: '/_dashboardLayout/courses/edit/$id'
      path: '/courses/edit/$id'
      fullPath: '/courses/edit/$id'
      preLoaderRoute: typeof DashboardLayoutCoursesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/channels/edit/$id': {
      id: '/_dashboardLayout/channels/edit/$id'
      path: '/channels/edit/$id'
      fullPath: '/channels/edit/$id'
      preLoaderRoute: typeof DashboardLayoutChannelsEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/broadcast/edit/$id': {
      id: '/_dashboardLayout/broadcast/edit/$id'
      path: '/broadcast/edit/$id'
      fullPath: '/broadcast/edit/$id'
      preLoaderRoute: typeof DashboardLayoutBroadcastEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/articles/edit/$id': {
      id: '/_dashboardLayout/articles/edit/$id'
      path: '/articles/edit/$id'
      fullPath: '/articles/edit/$id'
      preLoaderRoute: typeof DashboardLayoutArticlesEditIdRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/sections/$sectionId/edit': {
      id: '/_dashboardLayout/courses/sections/$sectionId/edit'
      path: '/courses/sections/$sectionId/edit'
      fullPath: '/courses/sections/$sectionId/edit'
      preLoaderRoute: typeof DashboardLayoutCoursesSectionsSectionIdEditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/_dashboardLayout/courses/lessons/$lessonId/edit': {
      id: '/_dashboardLayout/courses/lessons/$lessonId/edit'
      path: '/courses/lessons/$lessonId/edit'
      fullPath: '/courses/lessons/$lessonId/edit'
      preLoaderRoute: typeof DashboardLayoutCoursesLessonsLessonIdEditRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutArticlesIdRoute: typeof DashboardLayoutArticlesIdRoute
  DashboardLayoutArticlesNewRoute: typeof DashboardLayoutArticlesNewRoute
  DashboardLayoutBroadcastIdRoute: typeof DashboardLayoutBroadcastIdRoute
  DashboardLayoutBroadcastNewRoute: typeof DashboardLayoutBroadcastNewRoute
  DashboardLayoutChannelsIdRoute: typeof DashboardLayoutChannelsIdRoute
  DashboardLayoutCoursesNewRoute: typeof DashboardLayoutCoursesNewRoute
  DashboardLayoutInviteCodesIdRoute: typeof DashboardLayoutInviteCodesIdRoute
  DashboardLayoutInviteCodesNewRoute: typeof DashboardLayoutInviteCodesNewRoute
  DashboardLayoutUsersIdRoute: typeof DashboardLayoutUsersIdRoute
  DashboardLayoutActivityIndexRoute: typeof DashboardLayoutActivityIndexRoute
  DashboardLayoutAppLinksIndexRoute: typeof DashboardLayoutAppLinksIndexRoute
  DashboardLayoutAppSettingsIndexRoute: typeof DashboardLayoutAppSettingsIndexRoute
  DashboardLayoutArticlesIndexRoute: typeof DashboardLayoutArticlesIndexRoute
  DashboardLayoutBroadcastIndexRoute: typeof DashboardLayoutBroadcastIndexRoute
  DashboardLayoutChannelsIndexRoute: typeof DashboardLayoutChannelsIndexRoute
  DashboardLayoutCoursesIndexRoute: typeof DashboardLayoutCoursesIndexRoute
  DashboardLayoutDashboardIndexRoute: typeof DashboardLayoutDashboardIndexRoute
  DashboardLayoutEnrollmentsIndexRoute: typeof DashboardLayoutEnrollmentsIndexRoute
  DashboardLayoutInviteCodesIndexRoute: typeof DashboardLayoutInviteCodesIndexRoute
  DashboardLayoutResourcesIndexRoute: typeof DashboardLayoutResourcesIndexRoute
  DashboardLayoutUsersIndexRoute: typeof DashboardLayoutUsersIndexRoute
  DashboardLayoutArticlesEditIdRoute: typeof DashboardLayoutArticlesEditIdRoute
  DashboardLayoutBroadcastEditIdRoute: typeof DashboardLayoutBroadcastEditIdRoute
  DashboardLayoutChannelsEditIdRoute: typeof DashboardLayoutChannelsEditIdRoute
  DashboardLayoutCoursesEditIdRoute: typeof DashboardLayoutCoursesEditIdRoute
  DashboardLayoutInviteCodesEditIdRoute: typeof DashboardLayoutInviteCodesEditIdRoute
  DashboardLayoutCoursesLessonsLessonIdEditRoute: typeof DashboardLayoutCoursesLessonsLessonIdEditRoute
  DashboardLayoutCoursesSectionsSectionIdEditRoute: typeof DashboardLayoutCoursesSectionsSectionIdEditRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutArticlesIdRoute: DashboardLayoutArticlesIdRoute,
  DashboardLayoutArticlesNewRoute: DashboardLayoutArticlesNewRoute,
  DashboardLayoutBroadcastIdRoute: DashboardLayoutBroadcastIdRoute,
  DashboardLayoutBroadcastNewRoute: DashboardLayoutBroadcastNewRoute,
  DashboardLayoutChannelsIdRoute: DashboardLayoutChannelsIdRoute,
  DashboardLayoutCoursesNewRoute: DashboardLayoutCoursesNewRoute,
  DashboardLayoutInviteCodesIdRoute: DashboardLayoutInviteCodesIdRoute,
  DashboardLayoutInviteCodesNewRoute: DashboardLayoutInviteCodesNewRoute,
  DashboardLayoutUsersIdRoute: DashboardLayoutUsersIdRoute,
  DashboardLayoutActivityIndexRoute: DashboardLayoutActivityIndexRoute,
  DashboardLayoutAppLinksIndexRoute: DashboardLayoutAppLinksIndexRoute,
  DashboardLayoutAppSettingsIndexRoute: DashboardLayoutAppSettingsIndexRoute,
  DashboardLayoutArticlesIndexRoute: DashboardLayoutArticlesIndexRoute,
  DashboardLayoutBroadcastIndexRoute: DashboardLayoutBroadcastIndexRoute,
  DashboardLayoutChannelsIndexRoute: DashboardLayoutChannelsIndexRoute,
  DashboardLayoutCoursesIndexRoute: DashboardLayoutCoursesIndexRoute,
  DashboardLayoutDashboardIndexRoute: DashboardLayoutDashboardIndexRoute,
  DashboardLayoutEnrollmentsIndexRoute: DashboardLayoutEnrollmentsIndexRoute,
  DashboardLayoutInviteCodesIndexRoute: DashboardLayoutInviteCodesIndexRoute,
  DashboardLayoutResourcesIndexRoute: DashboardLayoutResourcesIndexRoute,
  DashboardLayoutUsersIndexRoute: DashboardLayoutUsersIndexRoute,
  DashboardLayoutArticlesEditIdRoute: DashboardLayoutArticlesEditIdRoute,
  DashboardLayoutBroadcastEditIdRoute: DashboardLayoutBroadcastEditIdRoute,
  DashboardLayoutChannelsEditIdRoute: DashboardLayoutChannelsEditIdRoute,
  DashboardLayoutCoursesEditIdRoute: DashboardLayoutCoursesEditIdRoute,
  DashboardLayoutInviteCodesEditIdRoute: DashboardLayoutInviteCodesEditIdRoute,
  DashboardLayoutCoursesLessonsLessonIdEditRoute:
    DashboardLayoutCoursesLessonsLessonIdEditRoute,
  DashboardLayoutCoursesSectionsSectionIdEditRoute:
    DashboardLayoutCoursesSectionsSectionIdEditRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
