"""add channel_members enum value

Revision ID: 1053d8244b76
Revises: 232aa4832d70
Create Date: 2025-11-28 23:09:16.186490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1053d8244b76'
down_revision: Union[str, Sequence[str], None] = '232aa4832d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE broadcastrecipienttype ADD VALUE IF NOT EXISTS 'channel_members'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
