"""Adding enabled_opencircle_branding

Revision ID: 1d6c73a075f6
Revises: 64cf262fbc61
Create Date: 2025-11-17 21:11:36.225354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1d6c73a075f6'
down_revision: Union[str, Sequence[str], None] = '64cf262fbc61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('enable_opencircle_branding', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'enable_opencircle_branding')
    # ### end Alembic commands ###
