"""update broadcast model

Revision ID: 232aa4832d70
Revises: 593648ef190a
Create Date: 2025-11-28 23:02:18.949237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '232aa4832d70'
down_revision: Union[str, Sequence[str], None] = '593648ef190a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcast', sa.Column('channel_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'broadcast', 'channel', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'broadcast', type_='foreignkey')
    op.drop_column('broadcast', 'channel_id')
    # ### end Alembic commands ###
