"""add broadcast model

Revision ID: 593648ef190a
Revises: f843c2a188ce
Create Date: 2025-11-28 22:40:44.637736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '593648ef190a'
down_revision: Union[str, Sequence[str], None] = 'f843c2a188ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_type', sa.Enum('ALL_USERS', 'TEST_EMAIL', name='broadcastrecipienttype'), nullable=False),
    sa.Column('test_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', name='broadcaststatus'), nullable=False),
    sa.Column('sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_subject'), 'broadcast', ['subject'], unique=False)
    op.create_table('broadcast_recipient',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='broadcastrecipientstatus'), nullable=False),
    sa.Column('sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_recipient_broadcast_id'), 'broadcast_recipient', ['broadcast_id'], unique=False)
    op.create_index(op.f('ix_broadcast_recipient_email'), 'broadcast_recipient', ['email'], unique=False)
    op.create_index(op.f('ix_broadcast_recipient_user_id'), 'broadcast_recipient', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_recipient_user_id'), table_name='broadcast_recipient')
    op.drop_index(op.f('ix_broadcast_recipient_email'), table_name='broadcast_recipient')
    op.drop_index(op.f('ix_broadcast_recipient_broadcast_id'), table_name='broadcast_recipient')
    op.drop_table('broadcast_recipient')
    op.drop_index(op.f('ix_broadcast_subject'), table_name='broadcast')
    op.drop_table('broadcast')
    # ### end Alembic commands ###
