"""Add user_presence table for tracking user activity

Revision ID: 64cf262fbc61
Revises: 9d4e9bce8ece
Create Date: 2025-11-15 13:02:23.549040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '64cf262fbc61'
down_revision: Union[str, Sequence[str], None] = '9d4e9bce8ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_presence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disconnected_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_presence_connected_at'), 'user_presence', ['connected_at'], unique=False)
    op.create_index(op.f('ix_user_presence_connection_id'), 'user_presence', ['connection_id'], unique=False)
    op.create_index(op.f('ix_user_presence_disconnected_at'), 'user_presence', ['disconnected_at'], unique=False)
    op.create_index(op.f('ix_user_presence_user_id'), 'user_presence', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_presence_user_id'), table_name='user_presence')
    op.drop_index(op.f('ix_user_presence_disconnected_at'), table_name='user_presence')
    op.drop_index(op.f('ix_user_presence_connection_id'), table_name='user_presence')
    op.drop_index(op.f('ix_user_presence_connected_at'), table_name='user_presence')
    op.drop_table('user_presence')
    # ### end Alembic commands ###
