"""adding featured course field

Revision ID: 9d4e9bce8ece
Revises: 849e3d83ebe3
Create Date: 2025-11-14 21:43:40.071775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '9d4e9bce8ece'
down_revision: Union[str, Sequence[str], None] = '849e3d83ebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('course', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE course SET is_featured = false WHERE is_featured IS NULL')
    # Make column NOT NULL
    op.alter_column('course', 'is_featured', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_featured')
    # ### end Alembic commands ###
