"""add_device_info_to_refresh_token

Revision ID: d307b309adfc
Revises: 1fba4de46b5b
Create Date: 2025-11-27 09:39:24.585674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd307b309adfc'
down_revision: Union[str, Sequence[str], None] = '1fba4de46b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_token', sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_token', sa.Column('browser', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_token', sa.Column('os', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_token', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_token', sa.Column('last_used_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'last_used_at')
    op.drop_column('refresh_token', 'ip_address')
    op.drop_column('refresh_token', 'os')
    op.drop_column('refresh_token', 'browser')
    op.drop_column('refresh_token', 'device_type')
    op.drop_column('refresh_token', 'device_name')
    # ### end Alembic commands ###
