"""add softdelete

Revision ID: f843c2a188ce
Revises: f52cc8e8d6ee
Create Date: 2025-11-28 12:02:48.640929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'f843c2a188ce'
down_revision: Union[str, Sequence[str], None] = 'f52cc8e8d6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_links', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_settings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channel', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channelmember', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('course', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_verification', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('enrolledcourse', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invite_code', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lesson', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('media', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notification', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notification_preferences', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('password_reset', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pending_notification_email', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('post', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('reaction', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('refresh_token', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resource', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('section', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('urlpreview', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_presence', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_settings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_social', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_social', 'deleted_at')
    op.drop_column('user_settings', 'deleted_at')
    op.drop_column('user_presence', 'deleted_at')
    op.drop_column('user', 'deleted_at')
    op.drop_column('urlpreview', 'deleted_at')
    op.drop_column('section', 'deleted_at')
    op.drop_column('resource', 'deleted_at')
    op.drop_column('refresh_token', 'deleted_at')
    op.drop_column('reaction', 'deleted_at')
    op.drop_column('post', 'deleted_at')
    op.drop_column('pending_notification_email', 'deleted_at')
    op.drop_column('password_reset', 'deleted_at')
    op.drop_column('notification_preferences', 'deleted_at')
    op.drop_column('notification', 'deleted_at')
    op.drop_column('media', 'deleted_at')
    op.drop_column('lesson', 'deleted_at')
    op.drop_column('invite_code', 'deleted_at')
    op.drop_column('enrolledcourse', 'deleted_at')
    op.drop_column('email_verification', 'deleted_at')
    op.drop_column('course', 'deleted_at')
    op.drop_column('channelmember', 'deleted_at')
    op.drop_column('channel', 'deleted_at')
    op.drop_column('app_settings', 'deleted_at')
    op.drop_column('app_links', 'deleted_at')
    op.drop_column('activity', 'deleted_at')
    # ### end Alembic commands ###
